/**
 * Curated fallback list of Indian colleges/universities, used to supplement the
 * hipolabs API in /api/colleges (many of these are missing upstream). Names keep
 * their common abbreviations so searches like "iit"/"nit"/"vit" match.
 *
 * Server-only data — imported solely by the colleges route, never the client.
 */
export const INDIAN_COLLEGES: string[] = [
  // IITs
  "Indian Institute of Technology Madras (IIT Madras)",
  "Indian Institute of Technology Delhi (IIT Delhi)",
  "Indian Institute of Technology Bombay (IIT Bombay)",
  "Indian Institute of Technology Kanpur (IIT Kanpur)",
  "Indian Institute of Technology Kharagpur (IIT KGP)",
  "Indian Institute of Technology Roorkee (IIT Roorkee)",
  "Indian Institute of Technology Guwahati (IITG)",
  "Indian Institute of Technology Hyderabad (IITH)",
  "Indian Institute of Technology (BHU) Varanasi (IIT BHU)",
  "Indian Institute of Technology (ISM) Dhanbad (IIT ISM)",
  "Indian Institute of Technology Indore (IITI)",
  "Indian Institute of Technology Ropar (IIT RPR)",
  "Indian Institute of Technology Mandi (IIT Mandi)",
  "Indian Institute of Technology Gandhinagar (IITGN)",
  "Indian Institute of Technology Jodhpur (IITJ)",
  "Indian Institute of Technology Patna (IITP)",
  "Indian Institute of Technology Bhubaneswar (IITBBS)",
  "Indian Institute of Technology Tirupati (IITT)",
  "Indian Institute of Technology Palakkad (IITPKD)",
  "Indian Institute of Technology Dharwad (IITDH)",
  "Indian Institute of Technology Jammu (IIT Jammu)",
  "Indian Institute of Technology Bhilai (IIT Bhilai)",
  "Indian Institute of Technology Goa (IIT Goa)",
  // NITs & IIEST
  "National Institute of Technology Tiruchirappalli (NIT Trichy)",
  "National Institute of Technology Karnataka, Surathkal (NIT Surathkal)",
  "National Institute of Technology Rourkela (NIT Rourkela)",
  "National Institute of Technology Warangal (NIT Warangal)",
  "National Institute of Technology Calicut (NIT Calicut)",
  "Motilal Nehru National Institute of Technology (MNNIT Allahabad)",
  "Visvesvaraya National Institute of Technology (VNIT Nagpur)",
  "Malaviya National Institute of Technology (MNIT Jaipur)",
  "National Institute of Technology Kurukshetra (NIT Kurukshetra)",
  "National Institute of Technology Silchar (NIT Silchar)",
  "National Institute of Technology Durgapur (NIT Durgapur)",
  "National Institute of Technology Jamshedpur (NIT Jamshedpur)",
  "National Institute of Technology Jalandhar (NIT Jalandhar)",
  "National Institute of Technology Hamirpur (NIT Hamirpur)",
  "National Institute of Technology Raipur (NIT Raipur)",
  "National Institute of Technology Patna (NIT Patna)",
  "National Institute of Technology Goa (NIT Goa)",
  "National Institute of Technology Agartala (NIT Agartala)",
  "National Institute of Technology Srinagar (NIT Srinagar)",
  "National Institute of Technology Delhi (NIT Delhi)",
  "National Institute of Technology Uttarakhand (NIT Uttarakhand)",
  "National Institute of Technology Mizoram (NIT Mizoram)",
  "National Institute of Technology Nagaland (NIT Nagaland)",
  "National Institute of Technology Manipur (NIT Manipur)",
  "National Institute of Technology Meghalaya (NIT Meghalaya)",
  "National Institute of Technology Arunachal Pradesh (NIT AP)",
  "National Institute of Technology Sikkim (NIT Sikkim)",
  "National Institute of Technology Andhra Pradesh (NIT AP)",
  "National Institute of Technology Puducherry (NIT Puducherry)",
  "National Institute of Technology Karaikal (NIT KKL)",
  "National Institute of Technology Sumari (NIT Garhwal)",
  "Indian Institute of Engineering Science and Technology, Shibpur (IIEST Shibpur)",
  // IIITs
  "Indian Institute of Information Technology, Allahabad (IIIT Allahabad)",
  "Atal Bihari Vajpayee IIITM, Gwalior (ABV-IIITM Gwalior)",
  "Indian Institute of Information Technology, Design & Manufacturing, Jabalpur (IIITDM)",
  "Indian Institute of Information Technology, Design & Manufacturing, Kancheepuram",
  "International Institute of Information Technology, Hyderabad (IIIT-H)",
  "International Institute of Information Technology, Bangalore (IIIT-B)",
  "Indian Institute of Information Technology, Guwahati (IIITG)",
  "Indian Institute of Information Technology, Kota (IIIT Kota)",
  "Indian Institute of Information Technology, Sri City (IIIT Sri City)",
  "Indian Institute of Information Technology, Vadodara (IIIT Vadodara)",
  "Indian Institute of Information Technology, Una (IIIT Una)",
  "Indian Institute of Information Technology, Kalyani (IIIT Kalyani)",
  "Indian Institute of Information Technology, Sonepat (IIIT Sonepat)",
  "Indian Institute of Information Technology, Trichy (IIIT Trichy)",
  "Indian Institute of Information Technology, Lucknow (IIIT Lucknow)",
  "Indian Institute of Information Technology, Dharwad (IIIT Dharwad)",
  "Indian Institute of Information Technology, Kottayam (IIIT Kottayam)",
  "Indian Institute of Information Technology, Manipur (IIIT Manipur)",
  "Indian Institute of Information Technology, Nagpur (IIIT Nagpur)",
  "Indian Institute of Information Technology, Pune (IIIT Pune)",
  "Indian Institute of Information Technology, Ranchi (IIIT Ranchi)",
  "Indian Institute of Information Technology, Surat (IIIT Surat)",
  "Indian Institute of Information Technology, Bhopal (IIIT Bhopal)",
  "Indian Institute of Information Technology, Bhagalpur (IIIT Bhagalpur)",
  "Indian Institute of Information Technology, Agartala (IIIT Agartala)",
  "Indian Institute of Information Technology, Raichur (IIIT Raichur)",
  // Science & research
  "Indian Institute of Science, Bangalore (IISc Bangalore)",
  "Indian Institute of Science Education and Research, Pune (IISER Pune)",
  "Indian Institute of Science Education and Research, Kolkata (IISER Kolkata)",
  "Indian Institute of Science Education and Research, Mohali (IISER Mohali)",
  "Indian Institute of Science Education and Research, Bhopal (IISER Bhopal)",
  "Indian Institute of Science Education and Research, Thiruvananthapuram (IISER TVM)",
  "Indian Institute of Science Education and Research, Tirupati (IISER Tirupati)",
  "Indian Institute of Science Education and Research, Berhampur (IISER Berhampur)",
  "National Institute of Science Education and Research, Bhubaneswar (NISER)",
  "Indian Statistical Institute, Kolkata (ISI Kolkata)",
  "Indian Statistical Institute, Delhi (ISI Delhi)",
  "Indian Statistical Institute, Bangalore (ISI Bangalore)",
  "Indian Agricultural Research Institute, New Delhi (IARI)",
  "Tata Institute of Fundamental Research, Mumbai (TIFR)",
  "Homi Bhabha National Institute, Mumbai (HBNI)",
  "Indian Institute of Space Science and Technology, Thiruvananthapuram (IIST)",
  // Top govt / state technical
  "Institute of Chemical Technology, Mumbai (ICT Mumbai)",
  "Delhi Technological University, Delhi (DTU)",
  "Netaji Subhas University of Technology, Delhi (NSUT)",
  "College of Engineering, Guindy (CEG Chennai)",
  "Jadavpur University, Faculty of Engineering, Kolkata",
  "PSG College of Technology, Coimbatore (PSG Tech)",
  "College of Engineering, Pune (COEP)",
  "Veermata Jijabai Technological Institute, Mumbai (VJTI)",
  "Harcourt Butler Technical University, Kanpur (HBTU)",
  "Madan Mohan Malaviya University of Technology, Gorakhpur (MMMUT)",
  "Guru Gobind Singh Indraprastha University (USIT), Delhi",
  "Indraprastha Institute of Information Technology, Delhi (IIIT Delhi)",
  "Andhra University College of Engineering, Visakhapatnam",
  "Jawaharlal Nehru Technological University, Hyderabad (JNTUH)",
  "Jawaharlal Nehru Technological University, Kakinada (JNTUK)",
  "Visvesvaraya Technological University, Belagavi (VTU)",
  "University Visvesvaraya College of Engineering, Bangalore (UVCE)",
  "Osmania University College of Engineering, Hyderabad",
  "Laxminarayan Institute of Technology, Nagpur (LIT)",
  "Punjab Engineering College, Chandigarh (PEC)",
  "Government College of Engineering, Amravati",
  "Walchand College of Engineering, Sangli",
  "Shri Govindram Seksaria Institute of Technology and Science, Indore (SGSITS)",
  "Jabalpur Engineering College, Jabalpur (JEC)",
  "Kamla Nehru Institute of Technology, Sultanpur (KNIT)",
  "Institute of Engineering and Technology, Lucknow (IET Lucknow)",
  "Bundelkhand Institute of Engineering & Technology, Jhansi (BIET)",
  "Cochin University of Science and Technology, Cochin (CUSAT)",
  "Government Engineering College, Thrissur",
  "College of Engineering, Trivandrum (CET)",
  "JNTU College of Engineering, Anantapur",
  "Sri Venkateswara University College of Engineering, Tirupati",
  "Kakatiya Institute of Technology & Science, Warangal",
  "University College of Engineering, Burla (VSSUT)",
  "Indira Gandhi Institute of Technology, Sarang (IGIT)",
  "Government College of Engineering, Kalahandi",
  "Jalpaiguri Government Engineering College, West Bengal",
  "Kalyani Government Engineering College, West Bengal",
  "Ghani Khan Choudhury Institute of Engineering and Technology, Malda",
  "Jorhat Engineering College, Assam",
  "Assam Engineering College, Guwahati",
  "Muzaffarpur Institute of Technology, Bihar",
  "Bhagalpur College of Engineering, Bihar",
  "Birsa Institute of Technology, Sindri (BIT Sindri)",
  "National Institute of Advanced Manufacturing Technology, Ranchi (NIAMT)",
  "Government Engineering College, Raipur",
  "L.D. College of Engineering, Ahmedabad",
  "Vishwakarma Government Engineering College, Ahmedabad",
  "Birla Vishvakarma Mahavidyalaya, Anand (BVM)",
  "MBM Engineering College, Jodhpur",
  "College of Technology and Engineering, Udaipur (CTAE)",
  "Government Engineering College, Ajmer",
  "Malnad College of Engineering, Hassan",
  // Private universities (South & West)
  "BITS Pilani (Main Campus)",
  "BITS Hyderabad Campus",
  "BITS Goa Campus",
  "VIT University, Vellore",
  "VIT University, Chennai",
  "Amrita Vishwa Vidyapeetham, Coimbatore",
  "Amrita Vishwa Vidyapeetham, Bengaluru",
  "SRM Institute of Science and Technology, Kattankulathur",
  "SRM University, Ramapuram",
  "Manipal Academy of Higher Education (MAHE), Manipal",
  "Manipal Institute of Technology, Bengaluru",
  "RV College of Engineering (RVCE), Bangalore",
  "BMS College of Engineering (BMSCE), Bangalore",
  "M.S. Ramaiah Institute of Technology (MSRIT), Bangalore",
  "PES University (Ring Road Campus), Bangalore",
  "PES University (Electronic City Campus), Bangalore",
  "Bangalore Institute of Technology (BIT), Bangalore",
  "Siddaganga Institute of Technology (SIT), Tumkur",
  "National NIE, Mysore",
  "SSN College of Engineering, Kalavakkam",
  "Sathyabama Institute of Science and Technology, Chennai",
  "Hindustan Institute of Technology and Science, Chennai",
  "Dr. M.G.R. Educational and Research Institute, Chennai",
  "Karunya Institute of Technology and Sciences, Coimbatore",
  "Kumaraguru College of Technology, Coimbatore",
  "Sri Krishna College of Engineering and Technology, Coimbatore",
  "Sona College of Technology, Salem",
  "Thiagarajar College of Engineering (TCE), Madurai",
  "Vel Tech Rangarajan Dr. Sagunthala R&D Institute, Chennai",
  "Bannari Amman Institute of Technology, Sathyamangalam",
  "Kongu Engineering College, Erode",
  "Meenakshi Sundararajan Engineering College, Chennai",
  "Panimalar Engineering College, Chennai",
  "Rajalakshmi Engineering College, Thandalam",
  "St. Joseph's College of Engineering, Chennai",
  "Easwari Engineering College, Chennai",
  "SASTRA Deemed University, Tanjore",
  "Chaitanya Bharathi Institute of Technology (CBIT), Hyderabad",
  "Vasavi College of Engineering, Hyderabad",
  "VNR Vignana Jyothi Institute of Engineering and Technology, Hyderabad",
  "Gokaraju Rangaraju Institute of Engineering and Technology, Hyderabad",
  "MVSR Engineering College, Hyderabad",
  "GRIET, Hyderabad",
  "CVR College of Engineering, Hyderabad",
  "Anurag University, Ghatkesar",
  "K L University (Koneru Lakshmaiah Education Foundation), Vaddeswaram",
  "GMR Institute of Technology, Rajam",
  "Gayatri Vidya Parishad College of Engineering, Visakhapatnam",
  "Velagapudi Ramakrishna Siddhartha Engineering College, Vijayawada",
  "Sree Vidyanikethan Engineering College, Tirupati",
  "Dhirubhai Ambani IICT (DA-IICT), Gandhinagar",
  "Nirma University, Ahmedabad",
  "Pandit Deendayal Energy University (PDEU), Gandhinagar",
  "Institute of Technology, Nirma University, Ahmedabad",
  "Symbiosis International University, Pune",
  "MIT World Peace University (MIT-WPU), Pune",
  "Vishwakarma Institute of Technology (VIT), Pune",
  "Cummins College of Engineering for Women, Pune",
  "Army Institute of Technology (AIT), Pune",
  "Singhad College of Engineering, Pune",
  "Pimpri Chinchwad College of Engineering (PCCOE), Pune",
  "NMIMS Mukesh Patel School of Technology, Mumbai",
  "Thadomal Shahani Engineering College (TSEC), Mumbai",
  "K.J. Somaiya College of Engineering, Mumbai",
  "Sardar Patel Institute of Technology (SPIT), Mumbai",
  "Dwarkadas J. Sanghvi College of Engineering (DJSCE), Mumbai",
  "Fr. Conceicao Rodrigues College of Engineering, Mumbai",
  "Vivekanand Education Society's Institute of Technology (VESIT), Mumbai",
  "R.A. Podar College of Commerce and Economics, Mumbai",
  "H.R. College of Commerce and Economics, Mumbai",
  "Jai Hind College, Mumbai",
  "Mithibai College of Arts, Mumbai",
  "Sophia College for Women, Mumbai",
  "St. Xavier's College, Mumbai",
  "Wilson College, Mumbai",
  "Elphinstone College, Mumbai",
  "K.J. Somaiya College of Arts and Commerce, Mumbai",
  "D.G. Ruparel College of Arts, Science and Commerce, Mumbai",
  "Ramnarain Ruia Autonomous College, Mumbai",
  "Sydenham College of Commerce and Economics, Mumbai",
  "Fergusson College, Pune",
  "Symbiosis College of Arts and Commerce, Pune",
  "Ness Wadia College of Commerce, Pune",
  "Nowrosjee Wadia College, Pune",
  "Brihan Maharashtra College of Commerce (BMCC), Pune",
  "Sir Parashurambhau College (SP College), Pune",
  "FLAME University, Pune",
  "Kirloskar Institute of Advanced Management Studies, Pune",
  "Praxis Business School, Pune",
  "International School of Business and Media (ISB&M), Pune",
  "ICFAI Foundation for Higher Education (IFHE), Hyderabad",
  "Woxsen University, Hyderabad",
  "GITAM Deemed University, Visakhapatnam",
  "GITAM University, Hyderabad Campus",
  "Mahindra University, Hyderabad",
  "Alliance University, Bangalore",
  "REVA University, Bangalore",
  "Jain University, Bangalore",
  "Dayananda Sagar University, Bangalore",
  "Azim Premji University, Bangalore",
  // Private universities (North, East & Central)
  "Thapar Institute of Engineering and Technology (TIET), Patiala",
  "Birla Institute of Technology (BIT), Mesra",
  "BIT Mesra, Ranchi Extension Campus",
  "BIT Mesra, Patna Extension Campus",
  "BIT Mesra, Deoghar Extension Campus",
  "Kalinga Institute of Industrial Technology (KIIT), Bhubaneswar",
  "Siksha 'O' Anusandhan (SOA) University, Bhubaneswar",
  "Centurion University of Technology and Management, Paralakhemundi",
  "CV Raman Global University, Bhubaneswar",
  "Silicon Institute of Technology, Bhubaneswar",
  "NIST University, Berhampur",
  "Lovely Professional University (LPU), Phagwara",
  "Chandigarh University, Mohali",
  "Chitkara University, Rajpura",
  "Chitkara University, Solan",
  "Amity University, Noida Main Campus",
  "Amity University, Gurgaon (Manesar)",
  "Amity University, Lucknow",
  "Amity University, Jaipur",
  "Amity University, Gwalior",
  "Amity University, Mumbai",
  "Amity University, Kolkata",
  "Amity University, Raipur",
  "Shiv Nadar University (SNU), Greater Noida",
  "Ashoka University, Sonepat",
  "O.P. Jindal Global University, Sonepat",
  "BML Munjal University, Sidhrawali",
  "NorthCap University, Gurugram",
  "Sushant University, Gurugram",
  "GD Goenka University, Gurugram",
  "KR Mangalam University, Gurugram",
  "Galgotias University, Greater Noida",
  "Galgotias College of Engineering and Technology, Greater Noida",
  "Sharda University, Greater Noida",
  "GL Bajaj Institute of Technology and Management, Greater Noida",
  "JSS Academy of Technical Education, Noida",
  "Ajay Kumar Garg Engineering College (AKGEC), Ghaziabad",
  "Krishna Institute of Engineering and Technology (KIET), Ghaziabad",
  "IMS Engineering College, Ghaziabad",
  "ABES Engineering College, Ghaziabad",
  "NIET, Greater Noida",
  "Jaypee Institute of Information Technology (JIIT), Noida",
  "Jaypee University of Information Technology (JUIT), Waknaghat",
  "Jaypee University of Engineering and Technology (JUET), Guna",
  "Graphic Era University, Dehradun",
  "Graphic Era Hill University, Bhimtal",
  "University of Petroleum and Energy Studies (UPES), Dehradun",
  "DIT University, Dehradun",
  "Uttaranchal University, Dehradun",
  "Quantum University, Roorkee",
  "LNM Institute of Information Technology (LNMIIT), Jaipur",
  "Banasthali Vidyapith, Banasthali",
  "Jaipur National University, Jaipur",
  "JECRC University, Jaipur",
  "Manipal University, Jaipur",
  "SKIT, Jaipur",
  "Poornima University, Jaipur",
  "Modi University of Science and Technology, Lakshmangarh",
  "Techno India University, Kolkata",
  "Heritage Institute of Technology, Kolkata",
  "Institute of Engineering and Management (IEM), Kolkata",
  "Haldia Institute of Technology, Haldia",
  "Netaji Subhash Engineering College, Kolkata",
  "RCC Institute of Information Technology, Kolkata",
  "Brainware University, Kolkata",
  "Adamas University, Barasat",
  "Sister Nivedita University, Kolkata",
  "JIS College of Engineering, Kalyani",
  "Narula Institute of Technology, Agarpara",
  "Future Institute of Engineering and Management, Kolkata",
  "IMS Unison University, Dehradun",
  "ICFAI University, Dehradun",
  "ICFAI University, Jaipur",
  "ICFAI University, Jharkhand",
  "ICFAI University, Himachal Pradesh",
  "Invertis University, Bareilly",
  "Teerthanker Mahaveer University, Moradabad",
  "Shobhit University, Meerut",
  "IIMT University, Meerut",
  "Integral University, Lucknow",
  "Babu Banarasi Das University (BBDU), Lucknow",
  "Shri Ramswaroop Memorial University, Lucknow",
  "Era University, Lucknow",
  "GLA University, Mathura",
  "Mangalayatan University, Aligarh",
  "NIU (Noida International University), Greater Noida",
  "Bennett University, Greater Noida",
  "Apeejay Stya University, Sohna",
  "Plaksha University, Mohali",
  "Shoolini University, Solan",
  "Eternal University, Baru Sahib",
  "Maharishi Markandeshwar University, Mullana",
  "Guru Kashi University, Talwandi Sabo",
  "RIMT University, Mandi Gobindgarh",
  "CT University, Ludhiana",
  "ITM University, Gwalior",
  "Medicaps University, Indore",
  "Oriental University, Indore",
  "Sage University, Indore",
  "Avantika University, Ujjain",
  // Medical
  "AIIMS New Delhi",
  "AIIMS Bhubaneswar",
  "AIIMS Jodhpur",
  "AIIMS Patna",
  "AIIMS Bhopal",
  "AIIMS Raipur",
  "AIIMS Rishikesh",
  "AIIMS Nagpur",
  "AIIMS Raebareli",
  "AIIMS Mangalagiri",
  "AIIMS Gorakhpur",
  "AIIMS Kalyani",
  "AIIMS Bathinda",
  "AIIMS Guwahati",
  "AIIMS Rajkot",
  "AIIMS Deoghar",
  "AIIMS Bibinagar",
  "AIIMS Jammu",
  "AIIMS Madurai",
  "PGIMER, Chandigarh",
  "Christian Medical College (CMC), Vellore",
  "NIMHANS, Bangalore",
  "Sanjay Gandhi Postgraduate Institute of Medical Sciences (SGPGIMS), Lucknow",
  "JIPMER, Puducherry",
  "King George's Medical University (KGMU), Lucknow",
  "Kasturba Medical College (KMC), Manipal",
  "Kasturba Medical College (KMC), Mangalore",
  "Armed Forces Medical College (AFMC), Pune",
  "Maulana Azad Medical College (MAMC), New Delhi",
  "Grant Medical College & Sir J.J. Group of Hospitals, Mumbai",
  "Madras Medical College (MMC), Chennai",
  "Lady Hardinge Medical College (LHMC), New Delhi",
  "Vardhman Mahavir Medical College & Safdarjung Hospital (VMMC), New Delhi",
  "University College of Medical Sciences (UCMS), Delhi",
  "Seth G.S. Medical College & KEM Hospital, Mumbai",
  "Lokmanya Tilak Municipal Medical College (Sion Hospital), Mumbai",
  "Topiwala National Medical College & Nair Hospital, Mumbai",
  "B.J. Medical College, Pune",
  "B.J. Medical College, Ahmedabad",
  "Christian Medical College (CMC), Ludhiana",
  "St. John's Medical College, Bangalore",
  "Bangalore Medical College and Research Institute (BMCRI), Bangalore",
  "Institute of Medical Sciences, BHU, Varanasi",
  "Jawaharlal Nehru Medical College, AMU, Aligarh",
  "Stanley Medical College, Chennai",
  "Kilpauk Medical College, Chennai",
  "Amrita School of Medicine, Kochi",
  "Government Medical College (GMC), Kozhikode",
  "Government Medical College (GMC), Thiruvananthapuram",
  "Osmania Medical College, Hyderabad",
  "Gandhi Medical College, Secunderabad",
  "Andhra Medical College, Visakhapatnam",
  "Sri Venkateswara Medical College, Tirupati",
  "Mysore Medical College and Research Institute, Mysore",
  "JSS Medical College, Mysore",
  "K.S. Hegde Medical Academy, Mangalore",
  "Father Muller Medical College, Mangalore",
  "Yenepoya Medical College, Mangalore",
  "Jawaharlal Nehru Medical College (JNMC), Belgaum",
  "Sri Siddhartha Medical College, Tumkur",
  "MGM Medical College, Navi Mumbai",
  "MGM Medical College, Aurangabad",
  "Dr. D.Y. Patil Medical College, Hospital and Research Centre, Pune",
  "Krishna Institute of Medical Sciences, Karad",
  "Smt. NHL Municipal Medical College, Ahmedabad",
  "Government Medical College, Surat",
  "Pandit Deendayal Upadhyay Medical College, Rajkot",
  "Government Medical College, Baroda",
  "Sawai Man Singh (SMS) Medical College, Jaipur",
  "Sardar Patel Medical College, Bikaner",
  "Ravindranath Tagore (RNT) Medical College, Udaipur",
  "Dr. S.N. Medical College, Jodhpur",
  "Government Medical College, Kota",
  "Institute of Postgraduate Medical Education and Research (IPGMER), Kolkata",
  "Medical College and Hospital, Kolkata",
  "Nil Ratan Sircar (NRS) Medical College and Hospital, Kolkata",
  "R.G. Kar Medical College and Hospital, Kolkata",
  "Calcutta National Medical College (CNMC), Kolkata",
  "Bankura Sammilani Medical College, Bankura",
  "Burdwan Medical College, Burdwan",
  "SCB Medical College, Cuttack",
  "MKCG Medical College, Berhampur",
  "VSS Medical College, Burla",
  "Patna Medical College and Hospital (PMCH), Patna",
  "Darbhanga Medical College and Hospital (DMCH), Laheriasarai",
  "Nalanda Medical College and Hospital (NMCH), Patna",
  "Indira Gandhi Institute of Medical Sciences (IGIMS), Patna",
  "Rajendra Institute of Medical Sciences (RIMS), Ranchi",
  "Mahatma Gandhi Memorial Medical College, Jamshedpur",
  "MGM Medical College, Indore",
  "Gajra Raja Medical College (GRMC), Gwalior",
  "Netaji Subhash Chandra Bose Medical College, Jabalpur",
  "Pt. J.N.M. Medical College, Raipur",
  "Government Medical College, Amritsar",
  "Guru Gobind Singh Medical College, Faridkot",
  "Pt. B.D. Sharma Postgraduate Institute of Medical Sciences (PGIMS), Rohtak",
  "Government Medical College and Hospital (GMCH), Sector 32, Chandigarh",
  "Sher-i-Kashmir Institute of Medical Sciences (SKIMS), Srinagar",
  // Business schools
  "IIM Ahmedabad",
  "IIM Bangalore",
  "IIM Calcutta",
  "IIM Kozhikode",
  "IIM Lucknow",
  "IIM Indore",
  "XLRI Jamshedpur",
  "FMS Delhi (Faculty of Management Studies)",
  "MDI Gurgaon (Management Development Institute)",
  "IIM Shillong",
  "IIM Udaipur",
  "IIM Tiruchirappalli",
  "IIM Ranchi",
  "IIM Rohtak",
  "IIM Raipur",
  "IIM Kashipur",
  "IIM Visakhapatnam",
  "IIM Nagpur",
  "IIM Amritsar",
  "IIM Bodh Gaya",
  "IIM Sirmaur",
  "IIM Sambalpur",
  "IIM Jammu",
  "IIM Mumbai (formerly NITIE)",
  "SPJIMR, Mumbai",
  "Indian School of Business (ISB), Hyderabad",
  "ISB Mohali Campus",
  "JBIMS, Mumbai (Jamnalal Bajaj)",
  "SIBM Pune (Symbiosis Institute)",
  "NMIMS School of Business Management, Mumbai",
  "Shailesh J. Mehta School of Management (SJMSOM), IIT Bombay",
  "Department of Management Studies (DoMS), IIT Delhi",
  "Vinod Gupta School of Management (VGSoM), IIT Kharagpur",
  "DoMS, IIT Madras",
  "IME Department, IIT Kanpur",
  "DoMS, IIT Roorkee",
  "Xavier Institute of Management (XIMB), Bhubaneswar",
  "IMI New Delhi (International Management Institute)",
  "IIFT New Delhi (Indian Institute of Foreign Trade)",
  "IIFT Kolkata Campus",
  "IIFT Kakinada Campus",
  "Goa Institute of Management (GIM), Sanquelim",
  "Great Lakes Institute of Management, Chennai",
  "Great Lakes Institute of Management, Gurgaon",
  "IMT Ghaziabad (Institute of Management Technology)",
  "IMT Nagpur",
  "IMT Hyderabad",
  "TAPMI, Manipal (T.A. Pai)",
  "FORE School of Management, New Delhi",
  "LBSIM, New Delhi (Lal Bahadur Shastri)",
  "BIMTECH, Greater Noida",
  "Amity Business School, Noida",
  "NIRMA University Institute of Management, Ahmedabad",
  "IRMA, Anand (Institute of Rural Management)",
  "MICA, Ahmedabad",
  "KIIT School of Management (KSOM), Bhubaneswar",
  "IMI Bhubaneswar",
  "XIM University, Bhubaneswar",
  "IMI Kolkata",
  "Department of Business Management, Calcutta University",
  "IISWBM, Kolkata",
  "XISS, Ranchi (Xavier Institute of Social Service)",
  "Synetic Business School, Ludhiana",
  "UBBS, Panjab University, Chandigarh",
  "University School of Management Studies (USMS), GGSIPU, Delhi",
  "Department of Financial Studies (DFS), Delhi University",
  "Delhi School of Economics (DSE), Delhi University",
  "SRCC GBO (Global Business Operations), Delhi University",
  "Jaipuria Institute of Management, Noida",
  "Jaipuria Institute of Management, Lucknow",
  "New Delhi Institute of Management (NDIM), New Delhi",
  "Fortune Institute of International Business (FIIB), New Delhi",
  "SOIL Institute of Management, Gurugram",
  "IIHMR University, Jaipur",
  "EDII (Entrepreneurship Development Institute of India), Gandhinagar",
  "Prestige Institute of Management and Research, Indore",
  // Central & state universities
  "Jawaharlal Nehru University (JNU), New Delhi",
  "University of Delhi (DU), Delhi",
  "University of Hyderabad (UoH), Hyderabad",
  "Aligarh Muslim University (AMU), Aligarh",
  "Jamia Millia Islamia (JMI), New Delhi",
  "Savitribai Phule Pune University (SPPU), Pune",
  "University of Calcutta, Kolkata",
  "University of Madras, Chennai",
  "Panjab University, Chandigarh",
  "Pondicherry University, Puducherry",
  "Visva-Bharati University, Santiniketan",
  "Gauhati University, Guwahati",
  "University of Jammu, Jammu",
  "University of Kashmir, Srinagar",
  "Mumbai University (MU), Mumbai",
  "Gujarat University, Ahmedabad",
  "Osmania University, Hyderabad",
  "Utkal University, Bhubaneswar",
  "Kurukshetra University, Kurukshetra",
  "Maharshi Dayanand University (MDU), Rohtak",
  "Banaras Hindu University (BHU), Varanasi",
  "Allahabad University, Prayagraj",
  "Babasaheb Bhimrao Ambedkar University (BBAU), Lucknow",
  "Lucknow University, Lucknow",
  "Chhatrapati Shahu Ji Maharaj University (CSJMU), Kanpur",
  "Deen Dayal Upadhyaya Gorakhpur University, Gorakhpur",
  "Dr. Ram Manohar Lohia Avadh University, Ayodhya",
  "Chaudhary Charan Singh University (CCSU), Meerut",
  "Mahatma Jyotiba Phule Rohilkhand University, Bareilly",
  "Bundelkhand University, Jhansi",
  "Dr. Bhimrao Ambedkar University, Agra",
  "Patna University, Patna",
  "Magadh University, Bodh Gaya",
  "Baba Saheb Bhimrao Ambedkar Bihar University, Muzaffarpur",
  "Tilka Manjhi Bhagalpur University, Bhagalpur",
  "Lalit Narayan Mithila University, Darbhanga",
  "Ranchi University, Ranchi",
  "Central University of Jharkhand, Ranchi",
  "Ravenshaw University, Cuttack",
  "Sambalpur University, Sambalpur",
  "Berhampur University, Berhampur",
  "Fakir Mohan University, Balasore",
  "Jadavpur University, Kolkata",
  "Presidency University, Kolkata",
  "Kalyani University, West Bengal",
  "Burdwan University, West Bengal",
  "Vidyasagar University, Midnapore",
  "North Bengal University, Siliguri",
  "Kazi Nazrul University, Asansol",
  "Dibrugarh University, Assam",
  "Tezpur University, Assam",
  "Assam University, Silchar",
  "Cotton University, Guwahati",
  "Rajiv Gandhi University, Itanagar",
  "Manipur University, Imphal",
  "Tripura University, Agartala",
  "Mizoram University, Aizawl",
  "Nagaland University, Kohima",
  "North-Eastern Hill University (NEHU), Shillong",
  "Sikkim University, Gangtok",
  "Central University of Punjab, Bathinda",
  "Guru Nanak Dev University (GNDU), Amritsar",
  "Punjabi University, Patiala",
  "Punjab Agricultural University (PAU), Ludhiana",
  "Himachal Pradesh University (HPU), Shimla",
  "Central University of Himachal Pradesh, Dharamshala",
  "Central University of Haryana, Mahendragarh",
  "Guru Jambheshwar University of Science and Technology, Hisar",
  "Deenbandhu Chhotu Ram University of Science and Technology, Murthal",
  "Central University of Jammu, Samba",
  "Central University of Kashmir, Ganderbal",
  "Shri Mata Vaishno Devi University (SMVDU), Katra",
  "Rajasthan University, Jaipur",
  "Mohanlal Sukhadia University (MLSU), Udaipur",
  "Jai Narain Vyas University (JNVU), Jodhpur",
  "Central University of Rajasthan, Kishangarh",
  "Maharaja Ganga Singh University, Bikaner",
  "Maharaja Sayajirao University of Baroda (MSU), Vadodara",
  "Saurashtra University, Rajkot",
  "Veer Narmad South Gujarat University (VNSGU), Surat",
  "Central University of Gujarat, Gandhinagar",
  "Devi Ahilya Vishwavidyalaya (DAVV), Indore",
  "Rani Durgavati Vishwavidyalaya (RDVV), Jabalpur",
  "Jiwaji University, Gwalior",
  "Barkatullah University, Bhopal",
  "Vikram University, Ujjain",
  "Indira Gandhi National Tribal University (IGNTU), Amarkantak",
  "Pt. Ravishankar Shukla University, Raipur",
  "Sant Gadge Baba Amravati University, Amravati",
  "Rashtrasant Tukadoji Maharaj Nagpur University (RTMNU), Nagpur",
  "Dr. Babasaheb Ambedkar Marathwada University (BAMU), Aurangabad",
  "Shivaji University, Kolhapur",
  "SNDT Women's University, Mumbai",
  "Andhra University, Visakhapatnam",
  "Sri Venkateswara University (SVU), Tirupati",
  "Acharya Nagarjuna University, Guntur",
  "Sri Krishnadevaraya University, Anantapur",
  "Kakatiya University, Warangal",
  "Bangalore University, Bangalore",
  "Mysore University, Mysore",
  "Karnataka University, Dharwad",
  "Kuvempu University, Shimoga",
  "Mangalore University, Mangalore",
  "Gulbarga University, Kalaburagi",
  "Central University of Karnataka, Kalaburagi",
  // Top arts/science/commerce colleges
  "Hindu College, Delhi University",
  "Miranda House, Delhi University",
  "Hansraj College, Delhi University",
  "Kirori Mal College, Delhi University",
  "St. Stephen's College, Delhi University",
  "Shri Ram College of Commerce (SRCC), Delhi University",
  "Lady Shri Ram College for Women (LSR), Delhi University",
  "Ramjas College, Delhi University",
  "Sri Venkateswara College, Delhi University",
  "Atma Ram Sanatan Dharma College (ARSD), Delhi University",
  "Deen Dayal Upadhyaya College, Delhi University",
  "Gargi College, Delhi University",
  "Jesus and Mary College (JMC), Delhi University",
  "Acharya Narendra Dev College, Delhi University",
  "Shaheed Sukhdev College of Business Studies (SSCBS), Delhi University",
  "Shaheed Bhagat Singh College, Delhi University",
  "Sri Guru Tegh Bahadur Khalsa College, Delhi University",
  "Sri Guru Gobind Singh College of Commerce, Delhi University",
  "Indraprastha College for Women, Delhi University",
  "Daulat Ram College, Delhi University",
  "Dyal Singh College, Delhi University",
  "Zakir Husain Delhi College, Delhi University",
  "PGDAV College, Delhi University",
  "Motilal Nehru College, Delhi University",
  "St. Xavier's College, Kolkata",
  "Ramakrishna Mission Vidyamandira, Howrah",
  "Ramakrishna Mission Residential College, Narendrapur",
  "Scottish Church College, Kolkata",
  "Bethune College, Kolkata",
  "Loreto College, Kolkata",
  "Asutosh College, Kolkata",
  "Maulana Azad College, Kolkata",
  "Presidency College, Chennai",
  "Loyola College, Chennai",
  "Madras Christian College (MCC), Chennai",
  "Stella Maris College, Chennai",
  "Women's Christian College (WCC), Chennai",
  "Ethiraj College for Women, Chennai",
  "PSGR Krishnammal College for Women, Coimbatore",
  "PSG College of Arts and Science, Coimbatore",
  "Bishop Heber College, Tiruchirappalli",
  "St. Joseph's College, Tiruchirappalli",
  "American College, Madurai",
  "Lady Doak College, Madurai",
  "Thiagarajar College, Madurai",
  "St. Xavier's College, Palayamkottai",
  "Mithibai College, Mumbai",
  "HR College of Commerce and Economics, Mumbai",
  "RA Podar College of Commerce and Economics, Mumbai",
  "Sydenham College, Mumbai",
  "Ramnarain Ruia College, Mumbai",
  "SIES College of Arts, Science and Commerce, Mumbai",
  "Bhavans College, Andheri, Mumbai",
  "NM College of Commerce and Economics, Mumbai",
  "Abasaheb Garware College, Pune",
  "Mount Carmel College, Bangalore",
  "Christ University, Bangalore",
  "St. Joseph's College, Bangalore",
  "Jyoti Nivas College, Bangalore",
  "St. Aloysius College, Mangalore",
  "St. Agnes College, Mangalore",
  "Yuvaraja's College, Mysore",
  "University College, Thiruvananthapuram",
  "Mar Ivanios College, Thiruvananthapuram",
  "Maharaja's College, Ernakulam",
  "St. Teresa's College, Ernakulam",
  "Sacred Heart College, Thevara",
  "St. Thomas College, Thrissur",
  "Farook College, Calicut",
  "CMS College, Kottayam",
  "Nizam College, Hyderabad",
  "Loyola Academy Degree and PG College, Secunderabad",
  "St. Francis College for Women, Secunderabad",
  "St. Ann's College for Women, Mehdipatnam, Hyderabad",
  "Andhra Loyola College, Vijayawada",
  "St. Xavier's College, Jaipur",
  "St. Xavier's College, Ahmedabad",
  "H.L. College of Commerce, Ahmedabad",
  "Holkar Science College, Indore",
  // Law, architecture, design & niche
  "National Law School of India University (NLSIU), Bangalore",
  "National Academy of Legal Studies and Research (NALSAR), Hyderabad",
  "West Bengal National University of Juridical Sciences (NUJS), Kolkata",
  "National Law University (NLUJ), Jodhpur",
  "National Law Institute University (NLIU), Bhopal",
  "Gujarat National Law University (GNLU), Gandhinagar",
  "Rajiv Gandhi National University of Law (RGNUL), Patiala",
  "National Law University, Odisha (NLUO), Cuttack",
  "National University of Advanced Legal Studies (NUALS), Kochi",
  "National Law University and Judicial Academy, Guwahati",
  "Chanakya National Law University (CNLU), Patna",
  "Dr. Ram Manohar Lohiya National Law University (RMLNLU), Lucknow",
  "National Law University, Delhi (NLUD)",
  "Hidayatullah National Law University (HNLU), Raipur",
  "Damodaram Sanjivayya National Law University (DSNLU), Visakhapatnam",
  "Tamil Nadu National Law University (TNNLU), Tiruchirappalli",
  "Maharashtra National Law University (MNLU), Mumbai",
  "Maharashtra National Law University (MNLU), Nagpur",
  "Government Law College (GLC), Mumbai",
  "ILS Law College, Pune",
  "School of Planning and Architecture (SPA), New Delhi",
  "School of Planning and Architecture (SPA), Bhopal",
  "School of Planning and Architecture (SPA), Vijayawada",
  "CEPT University, Ahmedabad",
  "Sir J.J. College of Architecture, Mumbai",
  "Chandigarh College of Architecture (CCA), Chandigarh",
  "National Institute of Pharmaceutical Education and Research (NIPER), Mohali",
  "NIPER Ahmedabad",
  "NIPER Hyderabad",
  "NIPER Kolkata",
  "NIPER Guwahati",
  "Jamia Hamdard, New Delhi",
  "Bombay College of Pharmacy (BCP), Mumbai",
  "Poona College of Pharmacy, Pune",
  "JSS College of Pharmacy, Ooty",
  "Manipal College of Pharmaceutical Sciences (MCOPS), Manipal",
  "National Institute of Fashion Technology (NIFT), Delhi",
  "NIFT Mumbai",
  "NIFT Bengaluru",
  "NIFT Chennai",
  "NIFT Kolkata",
  "NIFT Hyderabad",
  "NIFT Gandhinagar",
  "National Institute of Design (NID), Ahmedabad",
  "NID Bengaluru Campus",
  "NID Gandhinagar Campus",
  "Industrial Design Centre (IDC), IIT Bombay",
  "Department of Design (DoD), IIT Guwahati",
  "Tata Institute of Social Sciences (TISS), Mumbai",
  "Indian Institute of Mass Communication (IIMC), New Delhi",
  "Film and Television Institute of India (FTII), Pune",
  "Satyajit Ray Film and Television Institute (SRFTI), Kolkata",
  "National School of Drama (NSD), New Delhi",
  "Forest Research Institute (FRI), Dehradun",
]
